version: '3.8'

services:
  app:
    container_name: app-test
    image: app-test
    build:
      context: .
      target: test
    command: npm test
    env_file:
      - .env.test
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
